name: Validate Webpage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Validate-HTML:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: HTML Validation
      run: |
        docker run --rm -v $PWD:/workspace ghcr.io/validator/validator:latest /bin/bash -c "find /workspace -name '*.html' -exec vnu --errors-only --skip-non-html {} +"
